# Generated by Django 5.0.4 on 2024-06-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=9)),
                ('predicted_class', models.IntegerField(blank=True, null=True)),
                ('predicted_class_name', models.CharField(blank=True, max_length=30, null=True)),
                ('probability', models.TextField(blank=True, null=True)),
                ('eye_image', models.ImageField(upload_to='eye_images/')),
                ('gradcam_image', models.TextField(blank=True, null=True)),
                ('quadrants_image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('is_confirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('quadrant_analysis', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
