# Generated by Django 5.0.4 on 2024-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=9)),
                ('eye_image', models.ImageField(upload_to='eye_images/')),
                ('description', models.TextField(null=True)),
                ('is_confirm', models.BooleanField(default=False)),
            ],
        ),
    ]
