# Generated by Django 5.0.4 on 2024-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='quadrants_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
