# Generated by Django 5.0.4 on 2024-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_patient_quadrants_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('quadrant_analysis', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
